wtf

diff --git a/.github/workflows/patch.yaml b/.github/workflows/patch.yaml
--- a/.github/workflows/patch.yaml
+++ b/.github/workflows/patch.yaml
@@ -71,12 +71,12 @@ jobs:
         run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
-      - name: Configure Git
-        working-directory: working
-        run: |
-          git config --unset-all http.https://github.com/.extraheader '[Aa][Uu][Tt][Hh][Oo][Rr][Ii][Zz][Aa][Tt][Ii][Oo][Nn]:' || echo "Unable to unset extraheader."
-          git config --global url.https://${{ steps.app-token.outputs.token }}@github.com/.insteadOf git+ssh://git@github.com
-          git config --global url.git@github.com:.insteadOf https://github.com/
+      # - name: Configure Git
+      #   working-directory: working
+      #   run: |
+      #     git config --unset-all http.https://github.com/.extraheader '[Aa][Uu][Tt][Hh][Oo][Rr][Ii][Zz][Aa][Tt][Ii][Oo][Nn]:' || echo "Unable to unset extraheader."
+      #     git config --global url.https://${{ steps.app-token.outputs.token }}@github.com/.insteadOf git+ssh://git@github.com
+      #     git config --global url.git@github.com:.insteadOf https://github.com/
       - name: Configure Git User
         working-directory: working
         run: |
@@ -90,7 +90,7 @@ jobs:
       - name: Apply Patches
         working-directory: working
         run: |
-          git remote set-url origin 'https://github.com/${{ inputs.repo }}.git'
+          git remote set-url origin 'https://${{ steps.app-token.outputs.token }}@github.com/${{ inputs.repo }}.git'
           find "${{ github.workspace }}/patch/" -type f -iname *.patch -print0 | sort -z | xargs -r0 git am
           git tag -f ${{ inputs.version }}
       - name: Push to Branch
