Hun?

diff --git a/.github/workflows/patch.yaml b/.github/workflows/patch.yaml
--- a/.github/workflows/patch.yaml
+++ b/.github/workflows/patch.yaml
@@ -71,21 +71,22 @@ jobs:
         run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
         env:
           GH_TOKEN: ${{ steps.app-token.outputs.token }}
-      # - name: Configure Git
-      #   working-directory: working
-      #   run: |
-      #     git config --global url.https://${{ steps.app-token.outputs.token }}@github.com/.insteadOf git+ssh://git@github.com
-      #     git config --global url.git@github.com:.insteadOf https://github.com/
+      - name: Configure Git
+        working-directory: working
+        run: |
+          git config --unset-all http.https://github.com/.extraheader '[Aa][Uu][Tt][Hh][Oo][Rr][Ii][Zz][Aa][Tt][Ii][Oo][Nn]:' || echo "Unable to unset extraheader."
+          git config --global url.https://${{ steps.app-token.outputs.token }}@github.com/.insteadOf git+ssh://git@github.com
+          git config --global url.git@github.com:.insteadOf https://github.com/
       - name: Configure Git User
         working-directory: working
         run: |
-          # git config --global user.name "github-actions[bot]"
-          # git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
-          git config user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
-          git config user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          # git config user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
+          # git config user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
           # git config --unset-all http.https://github.com/.extraheader '[Aa][Uu][Tt][Hh][Oo][Rr][Ii][Zz][Aa][Tt][Ii][Oo][Nn]:' || echo "Unable to unset extraheader."
-          git config --unset-all http.https://github.com/.extraheader
-          git config --add http.https://github.com/.extraheader 'Authorization: Bearer ${{ steps.app-token.outputs.token }}'
+          # git config --unset-all http.https://github.com/.extraheader
+          # git config --add http.https://github.com/.extraheader 'Authorization: Bearer ${{ steps.app-token.outputs.token }}'
       - name: Apply Patches
         working-directory: working
         run: |
